version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:carbon-browsers
    steps:
      - run:
          name: whatever
          command: echo "please work"
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:carbon-browsers
    steps:
      - checkout
      - run:
          name: Set git identity
          command:   git config  user.email "noviny@thinkmill.com.au" && git config --global user.name "Noviny"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Authenticate with registry
          command: npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run:
          name: release
          command: yarn release
workflows:
  version: 2
  something:
    jobs:
      - test
      - build:
          filters:
            branches:
              only: master
