version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:carbon-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: release
          command: yarn release
