version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:carbon-browsers
    steps:
      - run:
        name: test
        command: echo just want to make sure this works
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:carbon-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Authenticate with registry
          command: npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run:
          name: release
          command: yarn release
workflows:
    version: 2
    jobs:
        - test
        - build

